<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('items')->delete();

        \DB::table('items')->insert(array (
            0 =>
            array (
                'id' => 1,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'Médaillon licorne',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-10 08:53:15',
                'updated_at' => '2020-05-10 08:53:15',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'Médaillon dragon',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-10 08:53:49',
                'updated_at' => '2020-05-10 08:53:49',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'Médaillon centaure',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-10 08:54:14',
                'updated_at' => '2020-05-10 08:54:14',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'Médaillon satyre',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-10 08:54:22',
                'updated_at' => '2020-05-10 08:54:22',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'Carafe de vin',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-11 19:44:55',
                'updated_at' => '2020-05-11 19:44:55',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Clé bleue',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:10',
                'updated_at' => '2020-05-18 18:07:10',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Clé rose',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:15',
                'updated_at' => '2020-05-18 18:07:15',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Clé verte',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:18',
                'updated_at' => '2020-05-18 18:07:18',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Clé violette',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:22',
                'updated_at' => '2020-05-18 18:07:22',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Clé à molette',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:29',
                'updated_at' => '2020-05-18 18:07:29',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Médaillon bronze',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:48',
                'updated_at' => '2020-05-18 18:07:48',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Médaillon argent',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:52',
                'updated_at' => '2020-05-18 18:07:52',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'story_id' => 7,
                'category' => NULL,
                'name' => 'Médaillon or',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-18 18:07:55',
                'updated_at' => '2020-05-18 18:07:55',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'story_id' => 9,
                'category' => NULL,
                'name' => 'Epée',
                'default_price' => 10,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-23 20:28:25',
                'updated_at' => '2020-05-23 20:28:25',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'story_id' => 12,
                'category' => NULL,
                'name' => 'Bâton magique',
                'default_price' => 10,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-29 14:46:44',
                'updated_at' => '2020-05-29 14:46:44',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'story_id' => 12,
                'category' => NULL,
                'name' => 'Ration',
                'default_price' => 2,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-29 14:47:05',
                'updated_at' => '2020-05-29 14:47:05',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'story_id' => 12,
                'category' => NULL,
                'name' => 'Allume-feu',
                'default_price' => 1,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-29 14:47:37',
                'updated_at' => '2020-05-29 14:47:37',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'story_id' => 12,
                'category' => NULL,
                'name' => 'Duvet',
                'default_price' => 1,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-05-29 14:52:34',
                'updated_at' => '2020-05-29 14:52:34',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'story_id' => 4,
                'category' => NULL,
                'name' => 'toto',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-01 20:08:40',
                'updated_at' => '2020-06-01 20:08:40',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'story_id' => 13,
                'category' => NULL,
                'name' => 'épeée courte',
                'default_price' => 1,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-02 15:02:52',
                'updated_at' => '2020-06-02 15:02:52',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'story_id' => 14,
                'category' => NULL,
                'name' => 'Test1',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-02 15:09:28',
                'updated_at' => '2020-06-02 15:09:28',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'story_id' => 14,
                'category' => NULL,
                'name' => 'Test2',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-02 15:09:34',
                'updated_at' => '2020-06-02 15:09:34',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'story_id' => 13,
                'category' => NULL,
                'name' => 'Manteau',
                'default_price' => 1,
                'single_use' => 0,
                'size' => 5.0,
                'is_unique' => 0,
                'created_at' => '2020-06-02 15:09:50',
                'updated_at' => '2020-06-02 15:09:50',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'story_id' => 15,
                'category' => NULL,
                'name' => 'Aspirateur d\'illusions',
                'default_price' => 0,
                'single_use' => 1,
                'size' => 5.0,
                'is_unique' => 0,
                'created_at' => '2020-06-20 07:55:55',
                'updated_at' => '2020-06-20 07:55:55',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'story_id' => 16,
                'category' => NULL,
                'name' => 'hache',
                'default_price' => 5,
                'single_use' => 0,
                'size' => 1.7,
                'is_unique' => 0,
                'created_at' => '2020-06-20 17:08:38',
                'updated_at' => '2020-06-20 17:08:38',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'story_id' => 17,
                'category' => 'Pantalons',
                'name' => 'Pantalon en jean',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 2.0,
                'is_unique' => 0,
                'created_at' => '2020-06-21 09:55:00',
                'updated_at' => '2020-06-21 09:55:00',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'story_id' => 17,
                'category' => 'Pantalons',
                'name' => 'Pantalon court',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.5,
                'is_unique' => 0,
                'created_at' => '2020-06-21 09:55:33',
                'updated_at' => '2020-06-21 09:55:33',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'story_id' => 17,
                'category' => 'Pantalons',
                'name' => 'Jogging',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:02:55',
                'updated_at' => '2020-06-21 10:02:55',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'story_id' => 17,
                'category' => 'Chemises',
                'name' => 'Chemise en  jean',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:03:09',
                'updated_at' => '2020-06-21 10:03:09',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'story_id' => 17,
                'category' => 'Chemises',
                'name' => 'Chemise à fleurs',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:03:28',
                'updated_at' => '2020-06-21 10:03:28',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'story_id' => 17,
                'category' => 'Chemises',
                'name' => 'Haut de survêtement',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:03:40',
                'updated_at' => '2020-06-21 10:03:40',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 33,
                'story_id' => 17,
                'category' => 'Chaussettes',
                'name' => 'Chaussettes',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 0.5,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:04:28',
                'updated_at' => '2020-06-21 10:04:28',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 34,
                'story_id' => 17,
                'category' => 'Sous-vêtements',
                'name' => 'Slip kangourou',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 0.5,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:05:09',
                'updated_at' => '2020-06-21 10:05:09',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 35,
                'story_id' => 17,
                'category' => 'Sous-vêtements',
                'name' => 'Caleçon long',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 0.5,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:05:16',
                'updated_at' => '2020-06-21 10:05:16',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 36,
                'story_id' => 17,
                'category' => 'Sous-vêtements',
                'name' => 'Boxer',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 0.5,
                'is_unique' => 0,
                'created_at' => '2020-06-21 10:05:21',
                'updated_at' => '2020-06-21 10:05:21',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 37,
                'story_id' => 19,
                'category' => 'Outils',
                'name' => 'Lentille',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 0.0,
                'is_unique' => 0,
                'created_at' => '2020-07-28 12:59:08',
                'updated_at' => '2020-07-28 12:59:08',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 40,
                'story_id' => 23,
                'category' => 'Potions',
                'name' => 'Potion d\'endurance',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 1,
                'created_at' => '2020-08-13 04:38:29',
                'updated_at' => '2020-08-13 04:38:29',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 41,
                'story_id' => 23,
                'category' => 'Potions',
                'name' => 'Potion de force',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 1,
                'created_at' => '2020-08-13 04:38:39',
                'updated_at' => '2020-08-13 04:38:39',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 42,
                'story_id' => 23,
                'category' => 'Médailles',
                'name' => 'Médaille du mérite',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 1,
                'created_at' => '2020-08-13 06:52:34',
                'updated_at' => '2020-08-13 06:52:34',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 43,
                'story_id' => 23,
                'category' => 'Clés',
                'name' => 'Clé de bronze',
                'default_price' => 0,
                'single_use' => 0,
                'size' => 1.0,
                'is_unique' => 1,
                'created_at' => '2020-08-13 06:57:35',
                'updated_at' => '2020-08-13 06:57:35',
                'deleted_at' => NULL,
            ),
        ));


    }
}
